[book]
title = "Zino开发框架中文教程"
authors = ["photino"]
language = "zh"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
additional-css = ["theme/style.css"]
git-repository-url = "https://github.com/photino/zino-docs-zh"
edit-url-template = "https://github.com/photino/zino-docs-zh/edit/main/{path}"
